#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: "jdbc:postgresql://ec2-54-175-243-75.compute-1.amazonaws.com:5432/dcv6ga9btuv2ol"
#    username: ypsswksknbnfce
#    password: c6bf23100858e91823a4de47ce22156842d3d18b967cb84f36acbcec6f449957
#    dbcp2:
#      remove-abandoned-on-borrow: true
#      remove-abandoned-timeout: 60
